version: 2.1
workflows:
  test-deploy:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run: node --version
          name: Install dependencies
          command: npm install
      - run:
          name: Run Test
          command: npm run test
        
  
